version: 2

references:

base_image: &base_image
  hashicorp/terraform:light

working_directory: &working_directory
  ~/s3_website

default_config: &default_config
  docker:
    - image: *base_image
  working_directory: *working_directory
  environment:
    AWS_DEFAULT_OUTPUT: json
    BASH_ENV: /root/.bashrc

repo_cache_key: &repo_cache_key
  v1-repo-{{ .Branch }}-{{ .Revision }}

# Step to restore repository from cache
restore_repo: &restore_repo
  restore_cache:
    key: *repo_cache_key

save_repo: &save_repo
  save_cache:
    key: *repo_cache_key
    paths:
      - *working_directory

set_terraform_environment: &set_terraform_environment
  run:
    name: set terraform environment
    command: |
      echo 'export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}' >> $BASH_ENV
      echo 'export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}' >> $BASH_ENV
      if [ "${CIRCLE_BRANCH}" == "master" ]; then
        echo 'export TERRAFORM_ENVIRONMENT=production' >> $BASH_ENV
      else
        echo 'export TERRAFORM_ENVIRONMENT=staging' >> $BASH_ENV
      fi

terraform_init: &terraform_init
  run:
    name: terraform init
    command: |
      source $BASH_ENV
      cd terraform/environments/$TERRAFORM_ENVIRONMENT
      terraform init

apply_job: &apply_job
  <<: *default_config
  steps:
    - *restore_repo
    - *set_terraform_environment
    - *terraform_init
    - attach_workspace:
        at: *working_directory
    - run:
        name: terraform apply
        command: |
          source $BASH_ENV
          cd terraform/environments/$TERRAFORM_ENVIRONMENT
          terraform apply --auto-approve ../../terraform.plan

jobs:

  build:
    <<: *default_config
    steps:
      - checkout
      - *set_terraform_environment
      - run:
          name: terraform validate
          command: |
            source $BASH_ENV
            cd terraform/environments/$TERRAFORM_ENVIRONMENT

            if [ $(terraform validate -check-variables=false) -gt 0 ]; then
              echo "Terraform validation failed:"
              echo

              git checkout -- .

              echo
              echo "Please run terraform validate -check-variables=false"
              exit 1
            fi
      - *save_repo

  plan:
    <<: *default_config
    steps:
      - *restore_repo
      - *set_terraform_environment
      - *terraform_init
      - run:
          name: terraform plan
          command: |
            source $BASH_ENV
            cd terraform/environments/$TERRAFORM_ENVIRONMENT
            terraform plan -out=../../terraform.plan
      - persist_to_workspace:
          root: *working_directory
          paths:
            - terraform.plan

  apply:
    <<: *apply_job
  apply-with-approval:
    <<: *apply_job

workflows:
  version: 2
  build_s3_website:
    jobs:
      - build:
          context: aws
      - plan:
          context: aws
          requires:
            - build
      - approve:
          context: aws
          type: approval
          requires:
            - plan
          filters:
            branches:
              only: master
      - apply-with-approval:
          context: aws
          requires:
            - approve
          filters:
            branches:
              only: master
      - apply:
          context: aws
          requires:
            - plan
          filters:
            branches:
              only: staging
